### ISSUE TITLE
Brush component

### ISSUE THREAD

**Issue by bsr203** [ihmeuw/beaut#4]
Hi,

I was looking for a d3 brush component which works with React and found your project. I don't have any interactivity for `range-slider` demo. Also, no callback on `Brush` to get the updated range. Just wonder about any plan to expand this component.

Your project looks very clean and of high quality. Thanks for open sourcing it.
Cheers,
bsr

**Comment by GabeMedrash** [comment]
Hi @bsr203, 

The brush component is a very early prototype and will eventually look and function similar to how it was implemented in [one of our visualizations](http://vizhub.healthdata.org/subnational/china). Our hope is to have an NPM installable version of this component before the end of the month.  But, exactly, we're planning on having it accept a callback that's called when the slider handles move and will make available either the slider position in pixel space or in data space.

Thanks for checking this out!

**Comment by bsr203** [comment]
thanks you for the quick response. I will watch this repo for updates. Please close this if you like. Thanks again.
